### ISSUE TITLE
chat issues

### ISSUE THREAD

**Issue by Franklee1995** [ND-Framework/ND_Core#18]
**Describe the bug**

**To Reproduce**
1. Go to 'chat'
2. type in  /darkweb ...
4. See nothing and no error

**Expected behavior**
a dark web message in chat.

**Screenshots**

**Additional context**
if on as leo it gives the error saying "error: ... cannot access this command"

**Comment by HearingSubset19** [comment]
I believe that it is the intended use.

**Comment by Franklee1995** [comment]
no like as civ it doesnt work either

**Comment by WLVF** [comment]
> no like as civ it doesnt work either

Has this been resolved for you yet?

**Comment by Andyyy7666** [comment]
Some people still experience this.
