### ISSUE TITLE
getPlayerServerInfo returns nil

### ISSUE THREAD

**Issue by realCallMeJ** [ND-Framework/ND_Core#45]
`NDCore.getPlayerServerInfo(source)` appears to always return `nil`, which would probably be the cause behind not being able to see departments in ND_Characters when they have a discord role ID, even if you have a matching role ID

heres how im checking this (in case ive done something wrong)
code:
![image](https://github.com/ND-Framework/ND_Core/assets/73816044/92dbdeb6-abe3-4fdd-9ff6-507d7f82554d)
output:
![image](https://github.com/ND-Framework/ND_Core/assets/73816044/ec845942-68a6-4075-9427-a0c140932eba)

**Comment by Andyyy7666** [comment]
I've fixed this, does it work for you?
https://github.com/ND-Framework/ND_Core/commit/4b106d36889e68d8f9090614922859e2a6ad7433

**Comment by Andyyy7666** [comment]
The issue was caused only when joining because the old temporary source was a string

**Comment by realCallMeJ** [comment]
yes, that has fixed the main part of the issue
however, i noticed that this hasn't resolved the problem i mentioned with ND_Characters
after a little more testing, it appears that when attempting to retrieve discord role info through `getPlayerServerInfo`, it returns `nil` unless the core has been restarted
**code:**
![image](https://github.com/ND-Framework/ND_Core/assets/73816044/55382074-4335-48f3-8ecf-28eba33e924e)
**output before core restart:**
![image](https://github.com/ND-Framework/ND_Core/assets/73816044/ed073d1b-be8e-4585-8186-eba44dcb0a66)
**output after core restart:**
![image](https://github.com/ND-Framework/ND_Core/assets/73816044/bd90f5ee-d02a-48d9-8df4-7f39090d19f0)

**Comment by Andyyy7666** [comment]
I don’t have that problem anymore after this change, are you sure you have the updated files?

**Comment by realCallMeJ** [comment]
yeah, i have the latest files and i've just double checked to make sure
here's a video that shows the issue better:
https://medal.tv/games/gta-v/clips/1JApsZcKd81tKO/d1337lyFaqxY?invite=cr-MSx5WGQsMzczNjk4LA
