### ISSUE TITLE
NDCore/Characters Jobs/Dept does not save.

### ISSUE THREAD

**Issue by TheStoicBear** [ND-Framework/ND_Core#47]
**Bug Description:**
When creating a new character in ND_Characters, the assigned role IDs do not get associated with the character as expected.

**To Reproduce:**
1. Navigate to the 'ND_Characters' module.
2. Click on the 'Create New Character' button.
3. Fill in the required information for the new character.
4. Select the desired roles for the character.
5. Complete the character creation process.

**Expected Behavior:**
Upon creating a new character, the selected role IDs should be assigned and associated with the character, reflecting the character's roles accurately.

**Screenshots:**
https://cdn.discordapp.com/attachments/1174595405871321198/1182429296833331322/SPOILER_image.png?ex=65971f18&is=6584aa18&hm=4d5525d41008d0ded0286aec6924705ea35828b26fe4e9fd0e7867dfe58cc6bf&
https://cdn.discordapp.com/attachments/1174595405871321198/1174814975152373800/image.png?ex=65971b35&is=6584a635&hm=fb8fdbf30d9885de4da04ed1e33176adb007332782878f48f955e159d2557788&
https://cdn.discordapp.com/attachments/1174595405871321198/1174811581536800829/image.png?ex=6597180b&is=6584a30b&hm=2ba6ced527af0709e150cf675d4a4c5131a4bc705b490814c277ebdf37f978e1&

**Additional Context:**
This issue impacts the proper functioning of the ND_Characters module, as the absence of assigned role IDs can lead to incorrect permissions, access, or functionality for the newly created character. It is crucial to address this bug to ensure the accurate representation of roles within the application.
When you login and create a character it will not load that you have the RoleID. 

Which then wont display in Departments.
Yet if you restart ND_Core then ensure ND_Characters it'll grab the role if your in game.

https://discord.com/channels/857672921912836116/1174595405871321198
https://streamable.com/tmeifg

**Comment by Andyyy7666** [comment]
https://github.com/ND-Framework/ND_Characters/commit/830831a5ea8e38a9948c3d135cf820f39f815950
