### ISSUE TITLE
Finicky Spawned Vehicle locks.

### ISSUE THREAD

**Issue by TheStoicBear** [ND-Framework/ND_Core#48]
**Bug Description:**
In the Vehicle System of ND_Core, there is an issue where vMenu cars are affected by the system's lock on public cars, preventing them from being unlocked and drivable whent the player exits then return entered the vehicle.

**To Reproduce:**
1. Utilize vMenu to spawn a vehicle in the FiveM environment(vMenu).
3. Exit the Spawned vehicle.
4. Observe that the system locks those spawned through vMenu.

**Expected Behavior:**
The Vehicle System should differentiate between public cars and those spawned via vMenu, allowing vMenu cars to remain unlockable and drivable even when the system enforces locks on public cars.

**Additional Context:**
This bug disrupts the intended functionality of the Vehicle System, particularly when interacting with vehicles spawned through vMenu.

**Comment by Andyyy7666** [comment]
Probably caused because entity doesn’t exist on entity created event, will double check and test tomorrow.

**Comment by Andyyy7666** [comment]
pushed a fix, needs further testing: https://github.com/ND-Framework/ND_Core/commit/8b0f2b010d47d174e21c10d7fcc247b2ede7f203
