### ISSUE TITLE
NoCharacters support for 2.0 potentially?

### ISSUE THREAD

**Issue by Legacy-TacticalGamingInteractive** [ND-Framework/ND_Core#49]
**Describe the solution you'd like**
NoCharacters update to potentially work with ND 2.0 if its even possible

**Describe alternatives you've considered**
The only alternative that the community at large suggested was some form of optional character selection/creation screen with some form of vMenu exports/integration to make them synced. So people could run both on their server at the same time if they wanted to. Then the players would just choose if they want to use the character creation screen by ND or stick with vMenu - But that sounds like a hell of lot more work. And likely not even possible.

**Additional context**
I know its rare and a unique request maybe, but our community absolutely seems to be against classic character jobs/creation as our entire server is built on standalone with ox resources and vMenu and all permissions are done with ACE not esx/qb style jobs.

**Comment by Andyyy7666** [comment]
ND v2 doesn’t need the NoCharacters resource. It can work without a character selection.

**Comment by Legacy-TacticalGamingInteractive** [comment]
> ND v2 doesn’t need the NoCharacters resource. It can work without a character selection.

Awesome! will be checking out 2.0 soon just waiting for full release and alll that kinda following updates as they go on here
