### ISSUE TITLE
/pay & Invoices

### ISSUE THREAD

**Issue by ValenciaModifcations** [ND-Framework/ND_Core#51]
**Describe the bug**
Without having the correct amount of money in cash, if you /pay somebody, they wrill recieve your money... lol

Also, invoices are bugged and will not allow you to pay them.

**To Reproduce**
1. Have a test subject, have 2500 in cash. 
2. /pay 8000
3. Check money amount. 
4. See problem.

**Expected behavior**
/pay is refused due to insufficent funds.

**Comment by Legacy-TacticalGamingInteractive** [comment]
> **Describe the bug** Without having the correct amount of money in cash, if you /pay somebody, they wrill recieve your money... lol
> 
> Also, invoices are bugged and will not allow you to pay them.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Have a test subject, have 2500 in cash.
> 2. /pay 8000
> 3. Check money amount.
> 4. See problem.
> 
> **Expected behavior** /pay is refused due to insufficent funds.

What is your inventory money amount. Is it the same as your ND hud amount or is it not syncing? Just asking for research purposes based on a different bug that might be related or not

**Comment by ValenciaModifcations** [comment]
The only way to check money is via Banks or Pause Menu in our server.

**Comment by Andyyy7666** [comment]
This should be fixed, I haven't had time to test it tho: https://github.com/ND-Framework/ND_Core/commit/d939607d6451995d8a2ea93d97c2b1ce993bbef3

Also invoices would be related to [ND Banking](https://github.com/ND-Framework/ND_Banking)

**Comment by Andyyy7666** [comment]
invoices issue moved to: https://github.com/ND-Framework/ND_Banking/issues/3
