### ISSUE TITLE
Ox Inventory not working with ND_Core

### ISSUE THREAD

**Issue by litbadman999** [ND-Framework/ND_Core#56]
OX told me this is a ND_Core issue, for some reason the Inventory thinks the Ped is dead and won't let you open the Inventory it will just say "Can't open Inventory right now" and gives a error.

Here is the link to the pic of the error:
https://media.discordapp.net/attachments/884511127608897557/1196181512438169651/image.png?ex=65b6b1d8&is=65a43cd8&hm=e9a8c42de734295c06730ab9bafb71c2cca9aece406fcc160876c692d94c6bbd&=&format=webp&quality=lossless

**Comment by Andyyy7666** [comment]
What version is your ND Core (check fxmanifest.lua)

**Comment by litbadman999** [comment]
I am on v2.1.1 and I have tried a couple older versions as well.

**Comment by Andyyy7666** [comment]
Are you using ND_Ambulance?

**Comment by litbadman999** [comment]
No, I use Scully ems menu

**Comment by Andyyy7666** [comment]
Hmmm, it could have something to do with it. Does that have anything to do with the player death?

**Comment by litbadman999** [comment]
Yes it does, and I have tried it without the script too

**Comment by litbadman999** [comment]
I have even took your death script out of the ND_Core fxmanifest I was told be your staff to try that for some reason it still didn't stop your death script from working, so maybe the error is bc of your death script and scullys ems menu both running at the same time? idk just a idea.

**Comment by Andyyy7666** [comment]
I'm not sure how it's happening as I'm not getting the issue myself. I'll be experimenting tomorrow and try to get it to happen to me.

**Comment by Andyyy7666** [comment]
Try reviving your player using `/revive` command

**Comment by litbadman999** [comment]
Yeah /revive works and take all the time you need.

**Comment by litbadman999** [comment]
How could I disable your framework death system?
