### ISSUE TITLE
Vehicle system

### ISSUE THREAD

**Issue by terrantdt** [ND-Framework/ND_Core#60]
**Describe the bug**
The vehicle system shows vehicles as nil and I can't use the vehicle system at all because of it 

**To Reproduce**
Unknown 

**Expected behavior**
When I buy a car and try to unlock it or try and push it to a garage and put it up I get a error code in my f8

**Screenshots**
![image](https://github.com/ND-Framework/ND_Core/assets/59056470/c1ee7820-8ecd-4ff5-8041-eb5fb68b1518)

![image](https://github.com/ND-Framework/ND_Core/assets/59056470/f4fed83f-0d36-407c-aa5d-65bd006424c0)

**Additional context**
Love your frame work keep up the good work

**Comment by Andyyy7666** [comment]
Thank you I'll look into this

**Comment by jnccloud** [comment]
> Thank you I'll look into this

Is this a true bug? ox_lib isn't up to date because the first screenshot shows a reference to client.lua:37 which is now shared.lua in ox_lib.

@terrantdt you should try using the [latest release](https://github.com/overextended/ox_lib/releases) of ox_lib and report back

**Comment by terrantdt** [comment]
it worked i thought i had the latest but i had it downloaded in 2 different places had to delete the old one

**Comment by jnccloud** [comment]
Awesome,  thanks for being kind and reporting back

**Comment by Andyyy7666** [comment]
😃
