### ISSUE TITLE
Sending all vehicles to garages/impound upon resource stop

### ISSUE THREAD

**Issue by marshular** [ND-Framework/ND_Core#61]
**Is your feature request related to a problem? Please describe.**
Not necessarily, but as of right now when you have a vehicle outside of the garage then stop the resource/stop the server, the vehicle is lost forever.

**Describe the solution you'd like**
On resource stop, return all owned vehicles to the garage/impound

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by Andyyy7666** [comment]
completed
