### ISSUE TITLE
Fatal Injury with ox_inventory

### ISSUE THREAD

**Issue by TheStoicBear** [ND-Framework/ND_Core#63]
**Describe the bug**
Users can not open their inventory. When viewing F8 it states it can not open the inventory cause the player is fatality injured. Only solution is to /revive [id].

**To Reproduce**
1. Die while using inventory with or without ND_Ambulance.
2. Relog, and attempt to open inventory.
3. This happens sometimes even without dying, on first join.

**Expected behavior**
A state for characterLoaded to see if player is truly fatally injured? So that when a player joins and is not dead they can use inventory. 

**Screenshots**
https://media.discordapp.net/attachments/1201345288737128458/1201351555174125648/image.png?ex=65c980d2&is=65b70bd2&hm=afa7bc58f8875e742bfee458dd51306842ab42b07bce6bee9549287f9b2be8ab&

**Additional context**
N/A

**Comment by Andyyy7666** [comment]
should be completely fixed now with new ambulance update.
